# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files, collect_submodules
a = Analysis(
    ['sidecar_app.py'],
    pathex=['..'],
    binaries=[],
    datas=[
        ('../templates', 'templates'),
        ('../static', 'static'),
    ] + list(collect_data_files('rapidocr', include_py_files=True)),
    hiddenimports=[
        'main',
        'ocr_engine',
        'field_extractor',
        'export',
        'invoice_config',
        'uvicorn.logging',
        'uvicorn.loops.auto',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan.on',
        'rapidocr',
        'fitz',
        'PIL',
        'numpy',
        'pandas',
        'openpyxl',
        'fastapi',
        'jinja2',
        # FastAPI dependencies
        'fastapi.middleware.cors',
        'fastapi.staticfiles',
        'fastapi.templating',
        'fastapi.responses',
        'fastapi.openapi',
        'fastapi.openapi.utils',
        'starlette.middleware.cors',
        'starlette.staticfiles',
        'starlette.templating',
        'starlette.responses',
        # Template dependencies
        'jinja2.ext',
        'jinja2.loaders',
        # PyMuPDF dependencies
        'PyMuPDF',
        'pymupdf',
        'pymupdf.fonts',
        # RapidOCR dependencies
        'rapidocr_onnxruntime',
        'rapidocr_onnxruntime.main',
        'rapidocr_onnxruntime.ch_ppocr_v2_det',
        'rapidocr_onnxruntime.ch_ppocr_v2_rec',
        'rapidocr_onnxruntime.ch_ppocr_v2_cls',
        'cv2',
        'onnxruntime',
        # Pillow
        'PIL.Image',
        'PIL._binary',
        'PIL.JpegImagePlugin',
        'PIL.PngImagePlugin',
        'PIL.BmpImagePlugin',
        'PIL.TiffImagePlugin',
        'PIL.GifImagePlugin',
        'PIL.WebPImagePlugin',
        # Uvicorn
        'uvicorn.main',
        'uvicorn.config',
        'uvicorn.lifespan',
        'uvicorn.server',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.loops',
        'uvicorn.loops.asyncio',
        'uvicorn.logging',
        'uvicorn.importer',
        'h11',
        'httptools',
        'websockets',
        'click',
        # Starlette
        'starlette.applications',
        'starlette.routing',
        'starlette.requests',
        'starlette.endpoints',
        'starlette.exceptions',
        'starlette.concurrency',
        'starlette.convertors',
        'starlette.background',
        'starlette.types',
        'starlette.formparsers',
        'starlette.datastructures',
        # Asyncio / concurrency
        'uvicorn.loops.asyncio',
        # Pillow
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['torch', 'torchvision', 'matplotlib', 'pytest', 'test', 'tests', 'IPython', 'notebook', 'scrapy', 'jupyterlab', 'nbformat', 'ipykernel'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='quickscan-sidecar',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='quickscan-sidecar',
)
